README.md

https://ssu-jira.softserveinc.com/browse/LVUIDF-0
Added this PR as example to show convention how to work with the code in this project.
To review:
Optional:
To merge:

LVUIDF-0: added extended description of project purpose.

---

app/assets/javascripts/app.js.jsx
app/assets/javascripts/application.js
app/assets/javascripts/routes.js.jsx
app/controllers/application_controller.rb
app/views/layouts/application.html.haml
config/routes.rb

https://ssu-jira.softserveinc.com/browse/LVUIDF-52
Created js assets structure and routes config
To review:
Optional:
To merge:

LVUIDF-52: create js assets structure

---

app/models/user.rb
app/views/layouts/application.html.haml
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20150709194238_devise_create_users.rb

Added user model through devise
To review:
Optional:
To merge:

LVUIDF-21: added devise user

---

app/assets/javascripts/collections/articles.js
app/assets/javascripts/components/articles/articles_destroy/DestroyArticle.js.jsx
app/assets/javascripts/components/articles/articles_edit/EditArticle.js.jsx
app/assets/javascripts/components/articles/articles_index/ArticleItem.js.jsx
app/assets/javascripts/components/articles/articles_index/Articles.js.jsx
app/assets/javascripts/components/articles/articles_index/ArticlesList.js.jsx
app/assets/javascripts/components/articles/articles_new/NewArticle.js.jsx
app/assets/javascripts/components/articles/articles_shared_components/forms/ArticleForm.js.jsx
app/assets/javascripts/components/articles/articles_shared_components/links/BackToArticlesLink.js.jsx
app/assets/javascripts/components/articles/articles_shared_components/links/EditArticleLink.jsx
app/assets/javascripts/components/articles/articles_shared_components/links/NewArticleLink.js.jsx
app/assets/javascripts/components/articles/articles_shared_components/status/ArticleStatus.js.jsx
app/assets/javascripts/components/articles/articles_show/Article.js.jsx
app/assets/javascripts/models/article.js
app/assets/javascripts/routes.js.jsx
app/controllers/api/v1/articles_controller.rb
app/models/article.rb
app/models/user.rb
config/routes.rb
db/migrate/20150710110000_create_articles.rb
db/migrate/20150710110005_create_articles_users_join_table.rb
db/seed.yml
db/seeds.rb

https://ssu-jira.softserveinc.com/browse/LVUIDF-31
Depends on PR #5 to add HABTM referrence
UPD: rebased
To review:
Optional:
To merge:

LVUIDF-31: create Article entity

---

app/assets/javascripts/components/pages/page_destroy.js.jsx
app/assets/javascripts/components/pages/page_form.js.jsx
app/assets/javascripts/components/pages/page_new.js.jsx
app/assets/javascripts/components/pages/page_show.js.jsx
app/assets/stylesheets/pages.scss
app/views/layouts/application.html.haml

Fixed 'Delete' button(Didn't work properly).
Replaced 'body' with 'page_container' (caused extra padding to all doc)
Deleted extra line.
To review:
To merge:

LVUIDF-24 Hotfix: Static pages layout.

---

app/assets/javascripts/app.js.jsx
app/assets/javascripts/application.js
app/assets/javascripts/collections/events.js
app/assets/javascripts/components/events/Event.js.jsx
app/assets/javascripts/components/events/EventEdit.js.jsx
app/assets/javascripts/components/events/EventForm.js.jsx
app/assets/javascripts/components/events/EventNew.js.jsx
app/assets/javascripts/components/events/Events.js.jsx
app/assets/javascripts/components/events/FieldEdit.js.jsx
app/assets/javascripts/components/events/FieldView.js.jsx
app/assets/javascripts/helpers/FormatHelpers.js.jsx
app/assets/javascripts/models/event.js
app/assets/javascripts/routes.js.jsx
app/assets/stylesheets/application.scss
app/controllers/api/v1/events_controller.rb
app/models/event.rb
config/routes.rb
db/migrate/20150714112731_create_events.rb
db/seed.yml
db/seeds.rb

To review:
Optional:
To merge:

LVUIDF-28: added updated version of Event entity.

---

app/assets/javascripts/collections/articles.js
app/assets/javascripts/components/_mixins/GetCurrentUserId.js.jsx
app/assets/javascripts/components/articles/articles_destroy/DestroyArticle.js.jsx
app/assets/javascripts/components/articles/articles_index/Articles.js.jsx
app/assets/javascripts/components/articles/articles_latest/LatestArticles.js.jsx
app/assets/javascripts/components/articles/articles_shared_components/forms/ArticleForm.js.jsx
app/assets/javascripts/components/articles/articles_shared_components/links/EditArticleLink.jsx
app/assets/javascripts/components/articles/articles_shared_components/links/NewArticleLink.js.jsx
app/assets/javascripts/components/articles/articles_shared_components/status/ArticleStatus.js.jsx
app/assets/javascripts/components/articles/articles_show/Article.js.jsx
app/assets/javascripts/components/layout/FrontPage.js.jsx
app/controllers/api/v1/articles_controller.rb
app/models/article.rb
app/views/layouts/application.html.haml
config/routes.rb

https://ssu-jira.softserveinc.com/browse/LVUIDF-57
Add links to 'Latest articles' on the front page
Make links available depending on user status
Refactor code
To review:
Optional:
To merge:

LVUIDF-57: Add 'Latest articles'

---

app/assets/javascripts/components/articles/articles_show/Article.js.jsx
app/controllers/api/v1/articles_controller.rb

https://ssu-jira.softserveinc.com/browse/LVUIDF-62
To review:
Optional:
To merge:

LVUIDF-62: prevent non-auth user from seeing article by direct link

---

app/assets/javascripts/components/pages/view/page_view.js.jsx
app/assets/javascripts/components/pages/view/pages_view.js.jsx
app/controllers/api/v1/pages_controller.rb
app/models/page.rb
spec/controllers/pages_controller_spec.rb
spec/factories/pages_factory.rb
spec/models/page_spec.rb

https://ssu-jira.softserveinc.com/browse/LVUIDF-64
To review:
To merge:

LVUIDF-64: Adding Rspec tests for model and controller.

---

spec/controllers/api/v1/pages_controller_spec.rb
spec/models/page_spec.rb

HOTFIX: Lvuidf-24:Deleted unneeded pieces, added api/v1 directory.

---

app/controllers/api/v1/articles_controller.rb
app/models/article.rb
spec/controllers/api/v1/articles_controller_spec.rb
spec/factories/articles_factory.rb
spec/factories/users_factory.rb
spec/models/article_spec.rb

https://ssu-jira.softserveinc.com/browse/LVUIDF-58
To review:
Optional:
To merge:

LVUIDF-58: cover Article with tests

---

.gitignore
Gemfile
app/assets/javascripts/application.js
app/assets/javascripts/components/events/EventsWidget.js.jsx
app/assets/javascripts/components/layout/FrontPage.js.jsx
app/assets/javascripts/helpers/FormatHelpers.js.jsx
app/models/event.rb

Implement events widget for main page.
To review:
To merge:

LVUIDF-28: add events widget

---

app/assets/javascripts/components/pages/page_form.js.jsx
app/assets/javascripts/tinymce_custom_options.js
app/controllers/api/v1/pages_controller.rb
app/models/page.rb
app/views/layouts/application.html.haml
db/migrate/20150710080653_create_pages.rb
spec/controllers/api/v1/pages_controller_spec.rb
spec/factories/pages_factory.rb
spec/models/page_spec.rb

Safe copy of https://github.com/dark-side/language-school/pull/41, reworked.
https://ssu-jira.softserveinc.com/browse/LVUIDF-66
To review:
To merge:

LVUIDF-66:Added initial TinyMCE

---

app/assets/javascripts/collections/comments.js
app/assets/javascripts/components/_mixins/CheckUserId.js.jsx
app/assets/javascripts/components/_mixins/ParseDate.js.jsx
app/assets/javascripts/components/articles/articles_show/Article.js.jsx
app/assets/javascripts/components/comments/_mixins/SetCommentUrl.js.jsx
app/assets/javascripts/components/comments/comments_destroy/DestroyComment.js.jsx
app/assets/javascripts/components/comments/comments_form/CommentForm.js.jsx
app/assets/javascripts/components/comments/comments_index/CommentItem.js.jsx
app/assets/javascripts/components/comments/comments_index/Comments.js.jsx
app/assets/javascripts/components/comments/comments_index/CommentsList.js.jsx
app/assets/javascripts/models/comment.js
app/controllers/api/v1/articles_controller.rb
app/controllers/api/v1/comments_controller.rb
app/controllers/application_controller.rb
app/models/article.rb
app/models/comment.rb
app/models/concerns/commentable.rb
app/models/user.rb
config/routes.rb
db/migrate/20150711113702_create_comments.rb

https://ssu-jira.softserveinc.com/browse/LVUIDF-35
UPD: reworked with nested resources
To review:
Optional:
To merge:

LVUIDF-35: create Comment entity

---

app/assets/javascripts/components/articles/articles_destroy/DestroyArticle.js.jsx
app/assets/javascripts/components/articles/articles_shared_components/forms/ArticleForm.js.jsx
app/assets/javascripts/components/comments/comments_form/CommentForm.js.jsx
spec/controllers/api/v1/articles_controller_spec.rb
spec/models/article_spec.rb

https://ssu-jira.softserveinc.com/browse/LVUIDF-48
To review:
To merge:

LVUIDF-48: add RTE to article

---

app/assets/stylesheets/page.scss

Only some minor style changes added
@rtriska please merge

LVUIDF-23:Hotfix-Some styles correcred

---

app/assets/javascripts/components/devise/_mixins/SetTokenMixin.js.jsx
app/assets/javascripts/components/devise/password_recovery/NewPassword.js.jsx
app/assets/javascripts/components/devise/sign_in/SignIn.js.jsx
app/assets/javascripts/components/devise/sign_in/SignInLink.js.jsx
app/assets/javascripts/components/devise/sign_out/SignOutLink.js.jsx
app/assets/javascripts/components/devise/sign_up/SignUp.js.jsx
app/assets/javascripts/components/devise/sign_up/SignUpLink.js.jsx
app/assets/javascripts/components/menu/menu_navbar.js.jsx
app/assets/javascripts/routes.js.jsx
app/assets/stylesheets/menu.scss
app/views/layouts/application.html.haml

https://ssu-jira.softserveinc.com/browse/LVUIDF-56
To review:
Optional:
To merge:

LVUIDF-56: rewrite Devise' views to React components

---

spec/controllers/api/v1/books_controller_spec.rb
spec/controllers/api/v1/events_controller_spec.rb
spec/factories/book_factory.rb
spec/factories/events_factory.rb
spec/models/book_spec.rb
spec/models/event_spec.rb

Rspec tests for event

---

spec/controllers/api/v1/menus_controller_spec.rb

Controller test added

---

app/controllers/manager_controller.rb
spec/controllers/api/v1/pages_controller_spec.rb

Just for Travis CI testing.
